[package]
name = "mode-logger"
version = "0.1.0"
authors = ["Erik Lilja <erikvlilja@gmail.com>"]
edition = "2018"

[dependencies]
zellij-tile = "0.32.0"
colored = "2.0.0"
regex = "1.3.3"

[build]
target = "wasm32-wasi"
